(function(root){
'use strict';
const cache=new Map();let host,canvas,caption,config,pictures,signature='',ticket=0,frame=0,reaction;
const reduced=root.matchMedia('(prefers-reduced-motion: reduce)');
function variant(token){let h=0;for(const c of String(token))h=(h*31+c.charCodeAt(0))>>>0;return h%3;}
function load(url){if(cache.has(url))return cache.get(url);const p=new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>{cache.delete(url);reject(new Error(url));};im.src=url+'?v=20260913-combat3';});cache.set(url,p);if(cache.size>12)cache.delete(cache.keys().next().value);return p;}
function mount(){if(host)return true;host=document.getElementById('combatScene');if(!host)return false;canvas=document.createElement('canvas');canvas.width=1536;canvas.height=1024;canvas.setAttribute('aria-hidden','true');caption=document.createElement('div');caption.className='combat-caption';caption.setAttribute('aria-live','polite');host.replaceChildren(canvas,caption);return true;}
function hide(){ticket++;signature='';config=pictures=reaction=null;cancelAnimationFrame(frame);frame=0;if(host)host.hidden=true;}
function draw(now=0){if(!config||!pictures||host.hidden)return;const ctx=canvas.getContext('2d'),elapsed=reaction?now-reaction.start:Infinity,active=elapsed>=0&&elapsed<870&&!reduced.matches;ctx.clearRect(0,0,1536,1024);ctx.drawImage(pictures[0],0,0,1536,1024);root.CombatLayout.drawCreature(ctx,pictures[1],config.species,active&&reaction.enemyAttack&&elapsed>=(reaction.shot?220:0)?Math.sin(Math.PI*Math.min(1,(elapsed-(reaction.shot?220:0))/650))*32:0);ctx.save();if(active&&reaction.shot)ctx.translate(0,Math.sin(Math.PI*Math.min(1,elapsed/220))*12);root.CombatLayout.drawForeground(ctx,pictures[2],pictures[3],config.weaponId);ctx.restore();caption.textContent=`${config.enemy.name} · ${Math.max(0,Number(config.enemy.hp)||0)} HP${config.pending?' · Ход выполняется…':''}`;host.setAttribute('aria-label','Бой: '+caption.textContent);}
async function show(next){if(!mount())return false;const token=next.enemy?.battleToken,visual=root.CombatAssets.getVisuals(next.enemy,variant(token)),weapon=root.COMBAT_ASSETS.pistols.find(w=>w.id===Number(next.weaponId)),armor=Number(next.armor);if(!token||!visual.ready||!weapon?.ready||!root.COMBAT_ASSETS.armorIds.includes(armor)){hide();return false;}config={...next,weaponId:weapon.id,species:visual.species,enemy:{...next.enemy}};const key=[token,visual.species,weapon.id,armor].join('|');if(signature===key){draw(performance.now());return true;}cancelAnimationFrame(frame);signature=key;pictures=reaction=null;host.hidden=true;const request=++ticket;try{const loaded=await Promise.all([visual.background,visual.mutant,'images/combat/'+weapon.image,`images/anomaly/hands/${armor}_right.webp`].map(load));if(request!==ticket)return false;pictures=loaded;host.hidden=false;draw(performance.now());return true;}catch(e){if(request===ticket)hide();return false;}}
function react(token,result,action){if(!config||token!==config.enemy.battleToken||!result?.success)return;if(action==='attack'&&Number.isFinite(result.enemyHp))config.enemy.hp=result.enemyHp;reaction={start:performance.now(),shot:action==='attack',enemyAttack:!!result.enemyTurn&&!result.victoryReady&&!result.died};cancelAnimationFrame(frame);function animate(now){frame=0;draw(now);if(config&&reaction&&!document.hidden&&!reduced.matches&&now-reaction.start<(reaction.shot?870:650))frame=requestAnimationFrame(animate);}if(!document.hidden)frame=requestAnimationFrame(animate);}
document.addEventListener('visibilitychange',()=>{cancelAnimationFrame(frame);frame=0;reaction=null;if(!document.hidden)draw(performance.now());});
root.CombatScene={show,hide,react};
})(window);
