const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(require.resolve('playwright',{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES]}));
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||undefined,args:['--no-sandbox'],headless:true});
 const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));let result={success:true,found:[],attempt:1,resolved:false};let searches=0;let release=null,delay=false;
 await page.route('**/*',async r=>{const u=new URL(r.request().url());if(u.pathname.endsWith('/api/raid/anomaly/search')){searches++;if(delay)await new Promise(resolve=>release=resolve);return r.fulfill({json:result})}if(u.pathname.includes('/api/'))return r.fulfill({json:[]});const file=path.join(process.cwd(),decodeURIComponent(u.pathname));if(fs.existsSync(file)&&fs.statSync(file).isFile())return r.fulfill({path:file});return r.abort();});
 let html=fs.readFileSync('index.html','utf8').replace(/<script\b[^>]*src=[^>]*><\/script>/g,'').replace('<head>','<head><base href="http://127.0.0.1/">');html=html.replace('</head>','<script>'+fs.readFileSync('images/anomaly/assets.js','utf8')+'</script><script>'+fs.readFileSync('images/anomaly/scene.js','utf8')+'</script></head>');
 await page.evaluate(()=>window.Telegram={WebApp:{initData:'',initDataUnsafe:{},ready(){},expand(){},setHeaderColor(){},setBackgroundColor(){}}});await page.setContent(html,{waitUntil:'domcontentloaded'});
 await page.evaluate(()=>{raidActive=true;raidSessionToken='offline-test';document.querySelectorAll('.screen').forEach(e=>e.classList.remove('active'));document.getElementById('mainMenu').style.display='none';document.getElementById('raidScreen').classList.add('active');startAnomalyEncounter({...anomalies[0],attemptsUsed:0,resolved:false});});
 const scene=page.locator('#anomalyScene');await scene.waitFor({state:'visible'});assert(await page.locator('.anomaly-found').isHidden());
 await page.evaluate(()=>searchForArtifact());assert(await page.locator('.anomaly-found').isHidden());
 result={success:true,found:['Медуза'],attempt:2,resolved:true};await page.evaluate(()=>searchForArtifact());assert(await page.locator('.anomaly-found').isVisible());await page.waitForFunction(()=>document.querySelector('.anomaly-artifact').naturalWidth>0);
 fs.mkdirSync('.validation/anomaly',{recursive:true});
 for(const width of [320,390,768]){await page.setViewportSize({width,height:1000});await page.waitForTimeout(350);await scene.screenshot({path:'.validation/anomaly/found_'+width+'.png'});const bounds=await scene.evaluate(e=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth}));assert(bounds.scroll<=bounds.viewport+1,JSON.stringify(bounds));}
 await page.evaluate(()=>{currentAnomaly=null;clearBattleUiAndRestoreNav()});assert(await scene.isHidden());
 await page.evaluate(()=>startAnomalyEncounter({...anomalies[1],attemptsUsed:0,resolved:false}));assert(await page.locator('.anomaly-found').isHidden());
 result={success:true,found:[],attempt:3,resolved:true};await page.evaluate(()=>searchForArtifact());assert(await page.locator('.anomaly-found').isHidden());
 await page.evaluate(()=>startAnomalyEncounter({...anomalies[0],resolved:false}));delay=true;const before=searches;await page.evaluate(()=>{window.pendingSearch=searchForArtifact();searchForArtifact()});await page.waitForFunction(()=>currentAnomaly._searchPending);while(!release)await new Promise(r=>setTimeout(r,10));assert.equal(searches,before+1);await page.evaluate(()=>{currentAnomaly=null;clearBattleUiAndRestoreNav()});result={success:true,found:['Медуза'],resolved:true};release();await page.evaluate(()=>window.pendingSearch);assert(await scene.isHidden());delay=false;
 const assets=await page.evaluate(()=>ANOMALY_ASSETS);for(const i of assets.armors){await page.evaluate(i=>AnomalyScene.show({armor:i,detector:'vizir.jpg',artifacts:[],anomaly:{id:2,name:'Электра'}}),i);await page.waitForFunction(i=>{const e=document.querySelector('.anomaly-right');return e.complete&&e.naturalWidth>0&&e.src.endsWith('/'+i+'_right.webp')},i);}
 for(const file of [...Object.values(assets.detectors),...Object.values(assets.artifacts)]){assert(fs.existsSync('images/anomaly/items/'+file),file)}
 for(const detector of Object.keys(assets.detectors)){await page.evaluate(detector=>AnomalyScene.show({armor:2,detector,artifacts:[],anomaly:{id:2,name:'Электра'}}),detector);await page.waitForFunction(file=>{const e=document.querySelector('.anomaly-detector');return e.complete&&e.naturalWidth>0&&e.src.endsWith('/'+file)},assets.detectors[detector]);await page.waitForTimeout(80);assert(await page.locator('.detector-display').evaluate(e=>e.getContext('2d').getImageData(0,0,e.width,e.height).data.some(v=>v)),'active display '+detector);await scene.screenshot({path:'.validation/anomaly/detector_'+detector+'.png'});}
 for(const [name,file] of Object.entries(assets.artifactNames)){await page.evaluate(name=>AnomalyScene.show({armor:2,detector:'vizir.jpg',artifacts:[{name}],anomaly:{id:2,name:'Электра'}}),name);await page.waitForFunction(file=>{const e=document.querySelector('.anomaly-artifact');return e.complete&&e.naturalWidth>0&&e.src.endsWith('/'+file)},file);}
 await page.evaluate(()=>AnomalyScene.show({armor:2,detector:'vizir.jpg',searching:true,anomaly:{id:2,name:'Электра'},artifacts:[]}));await page.waitForTimeout(150);const first=await page.locator('.detector-display').evaluate(e=>e.toDataURL());await page.waitForTimeout(250);assert.notEqual(await page.locator('.detector-display').evaluate(e=>e.toDataURL()),first,'detector scan moves');await scene.screenshot({path:'.validation/anomaly/animated-search.png'});await page.evaluate(()=>AnomalyScene.show({armor:2,detector:'vizir.jpg',searching:false,anomaly:{id:2,name:'Электра'},artifacts:[{name:'Медуза'}]}));await page.waitForTimeout(100);assert(await page.locator('.detector-display').evaluate(e=>!e.getContext('2d').getImageData(0,0,e.width,e.height).data.some(v=>v)),'screen stops after find');assert.equal(await page.locator('.anomaly-artifact').evaluate(e=>getComputedStyle(e).animationName),'artifact-life');await scene.screenshot({path:'.validation/anomaly/animated-found.png'});await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(100);assert.equal(await page.locator('.anomaly-artifact').evaluate(e=>getComputedStyle(e).animationName),'none');await page.evaluate(()=>AnomalyScene.hide());assert(await scene.isHidden());
 assert.equal(assets.armors.length,96);assert.equal(Object.keys(assets.detectors).length,9);assert.deepEqual(errors,[]);
 console.log('PASS: real client search/miss/found/close/restart; resolved without reward; 320/390/768 px; 96 sleeves; zero page errors; intercepted searches:',searches);await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
