'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict');
const hubs=fs.readFileSync('ui/trader-hubs.js','utf8');
const trade=fs.readFileSync('ui/trade-menu.js','utf8');
const css=fs.readFileSync('ui/trader-hubs.css','utf8');
const sound=fs.readFileSync('ui/pda-notification.mp3.b64','utf8').trim();
new Function(hubs); new Function(trade);
assert(Buffer.from(sound,'base64').subarray(0,3).toString()==='ID3');
assert(trade.includes("version: '1.3.0'"));
assert(trade.includes('openTradeItemInfoFromHold'));
assert(trade.includes('setTimeout(openTradeItemInfoFromHold, 520)'));
const clickBlock=trade.slice(trade.indexOf("root.addEventListener('click'"),trade.indexOf("el('tradeAuto').addEventListener"));
assert(!clickBlock.includes('showItemInfoModal(name)'),'short click must not show trade item info');
assert(clickBlock.includes("queues[source].delete(name)"));
assert(hubs.includes("/api/friends/pending"));
assert(hubs.includes('newFriendRequest'));
assert(hubs.includes("['dm','parcel','system','friend']"));
assert(hubs.includes("telegram.className=backpack.className"));
assert(css.includes('.pda-notification-friend'));
assert(!css.includes('#raidTelegramBtn{background:#34495e!important}'));
assert(css.includes('#gameAlertModal,#gameConfirmModal'));
console.log('interaction polish v2 static checks: OK');
