const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const patch=JSON.parse(fs.readFileSync('server_patches/pda_loadout.json','utf8'));
const source=patch.replacements[0].new.split("app.get('/api/player/:id'")[0];
const c=vm.createContext({getStableArmorKeyServer:n=>n.replace(/ \+\d+(?=[\u200B\u200C]*$)/,''),serverArtifactDef:n=>({name:n,tier:9,gen:4,isNamedArtifact:n==='Named',stats:{luck:5,radiationLeak:-3,invalid:Infinity},owner:'PRIVATE',price:999})});
vm.runInContext(source,c);
c.full={artifactSlots:['Named',null,'Hybrid\u200b',null,null,'Medusa','EXTRA'],armor:{name:'Armor +3\u200b'},armorUpgradeData:{'Armor\u200b':{armor:2,hitAbsorption:1},'Other':{armor:99}},inventory:{secret:1},warehouse:{secret:2},token:'SECRET'};
const before=JSON.stringify(c.full);const d=JSON.parse(vm.runInContext('JSON.stringify(publicEquippedLoadout(full))',c));
assert.deepEqual(d.artifactSlots,['Named',null,'Hybrid\u200b',null,null,'Medusa']);assert.equal(d.equippedArtifactDetails[1],null);assert.equal(d.equippedArtifactDetails[2].gen,4);assert.equal(d.equippedArtifactDetails[0].stats.invalid,undefined);assert.deepEqual(Object.keys(d.armorUpgradeData),['Armor\u200b']);assert.equal(d.armorUpgradeData['Armor\u200b'].hitAbsorption,1);assert.doesNotMatch(JSON.stringify(d),/PRIVATE|SECRET|inventory|warehouse|price/);assert.equal(JSON.stringify(c.full),before);
c.full={};const empty=JSON.parse(vm.runInContext('JSON.stringify(publicEquippedLoadout(full))',c));assert.deepEqual(empty.artifactSlots,Array(6).fill(null));assert.deepEqual(empty.armorUpgradeData,{});
console.log('PASS: public loadout preserves six positions, exact instance names and equipped stats; excludes private inventory and unrelated armor; does not mutate player');
