'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict');
const html=fs.readFileSync('index.html','utf8');
const quests=fs.readFileSync('ui/quests.js','utf8');
const hubs=fs.readFileSync('ui/trader-hubs.js','utf8');
const raid=fs.readFileSync('ui/raid-kpk-polish.js','utf8');
const css=fs.readFileSync('ui/raid-kpk-polish.css','utf8');
const wp=fs.readFileSync('ui/weapon-progression.js','utf8');
const data=require('../data/weapon-progression.json');

assert(html.includes('ui/raid-kpk-polish.css?v=20260919r1'));
assert(html.includes('ui/raid-kpk-polish.js?v=20260919r1'));
assert(html.includes('ui/weapon-progression.js?v=20260919w1'));
assert(html.includes('🪙 Сталбайты:')&&html.includes('🧬 Сталкоины:'));
assert(css.includes('grid-template-columns:repeat(2,minmax(0,1fr))'));
assert(css.includes('#raidVisualStage')&&css.includes('#raidUtilityButtons'));
assert(raid.includes("screen.querySelector('.zr-pda-banner')?.remove()"));
assert(raid.includes("anchor.insertAdjacentElement('afterend',log)"));
assert(quests.includes("const quick=document.getElementById('quickSlots')"));
assert(!quests.includes("response('Торговля','trade')"),'trade response still present in dialogue');
assert(hubs.includes('RAID_QUICK_INFO_HOLD_MS=800'));
assert(hubs.includes(".bunker-menu,#quickSlots"));
assert(wp.includes("adminExcluded:DATA.adminExcluded"));
assert.equal(data.entries.length,116);
assert(!data.entries.some(x=>x.name==='Убиваю взглядом'));
console.log('raid/PDA/quick-slot/weapon client static checks: OK');
