'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict');
const trade=fs.readFileSync('ui/trade-menu.js','utf8');
const patch=fs.readFileSync('server_patches/vendor_exclusive_stock_20260930.patch','utf8');
assert(trade.includes("markedPistols.length === 29"),'Zhuchara must expose all 29 pistols');
assert(trade.includes("regularArmorRange(1,29)"),'Zhuchara armor block 1-29 missing');
assert(trade.includes("markedShotguns.length === 29"),'Barman must expose all 29 shotguns');
assert(trade.includes("regularArmorRange(30,58)"),'Barman armor block 30-58 missing');
assert(trade.includes("progressionClass==='automatic'"),'Leonov automatic class missing');
assert(trade.includes("Number(a.id)>58"),'Leonov late armor block missing');
assert(!trade.includes("Number(w.tier)>=4&&Number(w.tier)<=Math.min(6,reachedZoneTier())"),'Barman must not be zone-tier truncated');
assert(!trade.includes("Number(w.tier)<=Math.min(3,reachedZoneTier())"),'Zhuchara must not be zone-tier truncated');
assert(patch.includes("cls==='pistol'"),'server Zhuchara pistol gate missing');
assert(patch.includes("cls==='shotgun'"),'server Barman shotgun gate missing');
assert(patch.includes("cls==='automatic'"),'server Leonov automatic gate missing');
assert(patch.includes("id>=1&&id<=29"),'server Zhuchara armor gate missing');
assert(patch.includes("id>=30&&id<=58"),'server Barman armor gate missing');
assert(patch.includes("id>58"),'server Leonov armor gate missing');
console.log('PASS: vendor stocks are exclusive and full within their assigned class/armor block');