'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict');
const trade=fs.readFileSync('ui/trade-menu.js','utf8');

assert(trade.includes("const isYantarLeonovContext"),'Yantar Leonov context detector missing');
assert(trade.includes("pos?.origin === 'yantar-bunker' && location === 6"),'Yantar Leonov must be location-scoped');
assert(trade.includes("w.progressionClass==='automatic'"),'Yantar Leonov must use the automatic weapon class');
assert(trade.includes("Number(w.tier)>=7&&Number(w.tier)<=Math.min(9,reached)"),'Yantar automatics must require reached T7-T9');
assert(trade.includes("const reached=reachedZoneTier()"),'Yantar reached-tier lookup missing');
assert(trade.includes("regularArmorByTier(7,reachedZoneTier())"),'Yantar ordinary armor must start at T7');
assert(trade.includes("a.isResearchSuit && !a.adminOnly"),'Research suits must remain available from Leonov');
assert(trade.includes("...yantarLeonovArmor().map"),'Yantar ordinary armor stock missing');
assert(trade.includes("sourceVendor = 'leonov-yantar'"),'Yantar purchase provenance missing');
assert(trade.includes("serverVendor = 'zhuchara'"),'Yantar regular gear must reuse the normal gear purchase route');
assert(trade.includes("!item?.isResearchSuit"),'research suits must stay on Leonov server validation');
assert(trade.includes("version: '1.5.0'"),'TradeMenu version mismatch');
assert(trade.includes("slot === 'weapon' || slot === 'armor'"),'Leonov must accept weapons and armor');
assert(trade.includes("vendorId === 'technician' && isVizir(item)")&&trade.includes("tokens:100"),'Vizir must cost 100 stalkcoins in Diesel trade');
assert(trade.includes("window.BunkerMenu?.openYantarWarehouse"),'Leonov trade warehouse must preserve Yantar return');
console.log('PASS: Yantar Leonov future T7+ stock is reached-zone gated; research suits and buyback remain wired');