/* Generated by tools/build_mutant_sound_manifest.cjs. */
(function(root){
'use strict';
const bank={
  "version": "combat-mutants-20260929-v1",
  "base": "audio/mutants/",
  "species": {
    "tushkan": {
      "name": "Тушкан",
      "tier": 0,
      "aliases": [
        "Тушкан"
      ],
      "hurt": {
        "files": [
          "tushkan-hurt-1.mp3",
          "tushkan-hurt-2.mp3",
          "tushkan-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "tushkan-attack-1.mp3",
          "tushkan-attack-2.mp3",
          "tushkan-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "blind-dog": {
      "name": "Слепая собака",
      "tier": 1,
      "aliases": [
        "Слепая собака",
        "Самка слепой собаки"
      ],
      "hurt": {
        "files": [
          "blind-dog-hurt-1.mp3",
          "blind-dog-hurt-2.mp3",
          "blind-dog-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "blind-dog-attack-1.mp3",
          "blind-dog-attack-2.mp3",
          "blind-dog-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "chernobyl-dog": {
      "name": "Чернобыльский пёс",
      "tier": 1,
      "aliases": [
        "Чернобыльский пёс",
        "Самка чернобыльского пса"
      ],
      "hurt": {
        "files": [
          "chernobyl-dog-hurt-1.mp3",
          "chernobyl-dog-hurt-2.mp3",
          "chernobyl-dog-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "chernobyl-dog-attack-1.mp3",
          "chernobyl-dog-attack-2.mp3",
          "chernobyl-dog-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "krakozyabra": {
      "name": "Кракозябра",
      "tier": 1,
      "aliases": [
        "Кракозябра",
        "Самка кракозябры"
      ],
      "hurt": {
        "files": [
          "krakozyabra-hurt-1.mp3",
          "krakozyabra-hurt-2.mp3",
          "krakozyabra-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "krakozyabra-attack-1.mp3",
          "krakozyabra-attack-2.mp3",
          "krakozyabra-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "flesh": {
      "name": "Плоть",
      "tier": 3,
      "aliases": [
        "Плоть",
        "Самка плоти"
      ],
      "hurt": {
        "files": [
          "flesh-hurt-1.mp3",
          "flesh-hurt-2.mp3",
          "flesh-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "flesh-attack-1.mp3",
          "flesh-attack-2.mp3",
          "flesh-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "boar": {
      "name": "Боров",
      "tier": 5,
      "aliases": [
        "Боров",
        "Самка борова"
      ],
      "hurt": {
        "files": [
          "boar-hurt-1.mp3",
          "boar-hurt-2.mp3",
          "boar-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "boar-attack-1.mp3",
          "boar-attack-2.mp3",
          "boar-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "isotope": {
      "name": "Изотоп",
      "tier": 5,
      "aliases": [
        "Изотоп",
        "Самка изотопа"
      ],
      "hurt": {
        "files": [
          "isotope-hurt-1.mp3",
          "isotope-hurt-2.mp3",
          "isotope-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "isotope-attack-1.mp3",
          "isotope-attack-2.mp3",
          "isotope-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "hinge": {
      "name": "Шарнир",
      "tier": 5,
      "aliases": [
        "Шарнир",
        "Самка шарнира"
      ],
      "hurt": {
        "files": [
          "hinge-hurt-1.mp3",
          "hinge-hurt-2.mp3",
          "hinge-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "hinge-attack-1.mp3",
          "hinge-attack-2.mp3",
          "hinge-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "zombie": {
      "name": "Зомби",
      "tier": 7,
      "aliases": [
        "Зомби",
        "Самка зомби"
      ],
      "hurt": {
        "files": [
          "zombie-hurt-1.mp3",
          "zombie-hurt-2.mp3",
          "zombie-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "zombie-attack-1.mp3",
          "zombie-attack-2.mp3",
          "zombie-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "pseudodog": {
      "name": "Псевдо собака",
      "tier": 9,
      "aliases": [
        "Псевдо собака",
        "Псевдособака",
        "Самка псевдо собаки"
      ],
      "hurt": {
        "files": [
          "pseudodog-hurt-1.mp3",
          "pseudodog-hurt-2.mp3",
          "pseudodog-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "pseudodog-attack-1.mp3",
          "pseudodog-attack-2.mp3",
          "pseudodog-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "lynx": {
      "name": "Рысь",
      "tier": 9,
      "aliases": [
        "Рысь",
        "Самка рыси"
      ],
      "hurt": {
        "files": [
          "lynx-hurt-1.mp3",
          "lynx-hurt-2.mp3",
          "lynx-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "lynx-attack-1.mp3",
          "lynx-attack-2.mp3",
          "lynx-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "chupacabra": {
      "name": "Чупакабра",
      "tier": 9,
      "aliases": [
        "Чупакабра",
        "Самка чупакабры"
      ],
      "hurt": {
        "files": [
          "chupacabra-hurt-1.mp3",
          "chupacabra-hurt-2.mp3",
          "chupacabra-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "chupacabra-attack-1.mp3",
          "chupacabra-attack-2.mp3",
          "chupacabra-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "psydog": {
      "name": "Пси собака",
      "tier": 11,
      "aliases": [
        "Пси собака",
        "Пси-собака",
        "Самка пси собаки"
      ],
      "hurt": {
        "files": [
          "psydog-hurt-1.mp3",
          "psydog-hurt-2.mp3",
          "psydog-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "psydog-attack-1.mp3",
          "psydog-attack-2.mp3",
          "psydog-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "bayun": {
      "name": "Кот Баюн",
      "tier": 11,
      "aliases": [
        "Кот Баюн",
        "Самка кота баюна"
      ],
      "hurt": {
        "files": [
          "bayun-hurt-1.mp3",
          "bayun-hurt-2.mp3",
          "bayun-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "bayun-attack-1.mp3",
          "bayun-attack-2.mp3",
          "bayun-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "snork": {
      "name": "Снорк",
      "tier": 13,
      "aliases": [
        "Снорк",
        "Самка снорка"
      ],
      "hurt": {
        "files": [
          "snork-hurt-1.mp3",
          "snork-hurt-2.mp3",
          "snork-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "snork-attack-1.mp3",
          "snork-attack-2.mp3",
          "snork-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "stregun": {
      "name": "Стрегун",
      "tier": 13,
      "aliases": [
        "Стрегун",
        "Самка стрегуна"
      ],
      "hurt": {
        "files": [
          "stregun-hurt-1.mp3",
          "stregun-hurt-2.mp3",
          "stregun-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "stregun-attack-1.mp3",
          "stregun-attack-2.mp3",
          "stregun-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "owl": {
      "name": "Филин",
      "tier": 13,
      "aliases": [
        "Филин",
        "Самка филина"
      ],
      "hurt": {
        "files": [
          "owl-hurt-1.mp3",
          "owl-hurt-2.mp3",
          "owl-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "owl-attack-1.mp3",
          "owl-attack-2.mp3",
          "owl-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "bloodsucker": {
      "name": "Кровосос",
      "tier": 15,
      "aliases": [
        "Кровосос",
        "Самка кровососа"
      ],
      "hurt": {
        "files": [
          "bloodsucker-hurt-1.mp3",
          "bloodsucker-hurt-2.mp3",
          "bloodsucker-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "bloodsucker-attack-1.mp3",
          "bloodsucker-attack-2.mp3",
          "bloodsucker-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "poltergeist": {
      "name": "Полтергейст",
      "tier": 17,
      "aliases": [
        "Полтергейст",
        "Самка полтергейста"
      ],
      "hurt": {
        "files": [
          "poltergeist-hurt-1.mp3",
          "poltergeist-hurt-2.mp3",
          "poltergeist-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "poltergeist-attack-1.mp3",
          "poltergeist-attack-2.mp3",
          "poltergeist-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "fire-poltergeist": {
      "name": "Огненный полтергейст",
      "tier": 19,
      "aliases": [
        "Огненный полтергейст",
        "Самка огненного полтергейста"
      ],
      "hurt": {
        "files": [
          "fire-poltergeist-hurt-1.mp3",
          "fire-poltergeist-hurt-2.mp3",
          "fire-poltergeist-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "fire-poltergeist-attack-1.mp3",
          "fire-poltergeist-attack-2.mp3",
          "fire-poltergeist-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "fracture": {
      "name": "Излом",
      "tier": 19,
      "aliases": [
        "Излом",
        "Самка излома"
      ],
      "hurt": {
        "files": [
          "fracture-hurt-1.mp3",
          "fracture-hurt-2.mp3",
          "fracture-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "fracture-attack-1.mp3",
          "fracture-attack-2.mp3",
          "fracture-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "burer": {
      "name": "Бюрер",
      "tier": 21,
      "aliases": [
        "Бюрер",
        "Самка бюрера"
      ],
      "hurt": {
        "files": [
          "burer-hurt-1.mp3",
          "burer-hurt-2.mp3",
          "burer-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "burer-attack-1.mp3",
          "burer-attack-2.mp3",
          "burer-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "moose": {
      "name": "Лось",
      "tier": 21,
      "aliases": [
        "Лось",
        "Самка лося"
      ],
      "hurt": {
        "files": [
          "moose-hurt-1.mp3",
          "moose-hurt-2.mp3",
          "moose-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "moose-attack-1.mp3",
          "moose-attack-2.mp3",
          "moose-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "controller": {
      "name": "Контролёр",
      "tier": 23,
      "aliases": [
        "Контролёр",
        "Самка контролёра"
      ],
      "hurt": {
        "files": [
          "controller-hurt-1.mp3",
          "controller-hurt-2.mp3",
          "controller-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "controller-attack-1.mp3",
          "controller-attack-2.mp3",
          "controller-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "stronglav": {
      "name": "Стронглав",
      "tier": 23,
      "aliases": [
        "Стронглав",
        "Самка стронглава"
      ],
      "hurt": {
        "files": [
          "stronglav-hurt-1.mp3",
          "stronglav-hurt-2.mp3",
          "stronglav-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "stronglav-attack-1.mp3",
          "stronglav-attack-2.mp3",
          "stronglav-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "chimera": {
      "name": "Химера",
      "tier": 25,
      "aliases": [
        "Химера",
        "Самка химеры"
      ],
      "hurt": {
        "files": [
          "chimera-hurt-1.mp3",
          "chimera-hurt-2.mp3",
          "chimera-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "chimera-attack-1.mp3",
          "chimera-attack-2.mp3",
          "chimera-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "electrochimera": {
      "name": "Электро химера",
      "tier": 25,
      "aliases": [
        "Электро химера",
        "Электрохимера",
        "Самка электро химеры"
      ],
      "hurt": {
        "files": [
          "electrochimera-hurt-1.mp3",
          "electrochimera-hurt-2.mp3",
          "electrochimera-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "electrochimera-attack-1.mp3",
          "electrochimera-attack-2.mp3",
          "electrochimera-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "observer": {
      "name": "Наблюдатель",
      "tier": 25,
      "aliases": [
        "Наблюдатель",
        "Самка наблюдателя"
      ],
      "hurt": {
        "files": [
          "observer-hurt-1.mp3",
          "observer-hurt-2.mp3",
          "observer-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "observer-attack-1.mp3",
          "observer-attack-2.mp3",
          "observer-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    },
    "pseudogiant": {
      "name": "Псевдогигант",
      "tier": 27,
      "aliases": [
        "Псевдогигант",
        "Самка псевдогиганта"
      ],
      "hurt": {
        "files": [
          "pseudogiant-hurt-1.mp3",
          "pseudogiant-hurt-2.mp3",
          "pseudogiant-hurt-3.mp3"
        ],
        "gain": 0.85
      },
      "attack": {
        "files": [
          "pseudogiant-attack-1.mp3",
          "pseudogiant-attack-2.mp3",
          "pseudogiant-attack-3.mp3"
        ],
        "gain": 0.85,
        "impactMs": 120
      }
    }
  }
};
// Male and female names share one species bank. Gameplay and art spellings
// differ for some species, so audio resolves independently of visual readiness.
const normalize=value=>String(value||'').normalize('NFC').toLowerCase().replace(/ё/g,'е').replace(/[\s\-–—]+/g,'');
const aliases=new Map();
for(const [id,species] of Object.entries(bank.species))for(const alias of species.aliases){
 const key=normalize(alias);
 if(aliases.has(key)&&aliases.get(key)!==id)throw Error('Ambiguous mutant sound alias: '+alias);
 aliases.set(key,id);
}
bank.resolve=function(enemy){
 if(!enemy||enemy.kind==='npc'||!(enemy.kind==='mutant'||enemy.mutant===true||enemy.isMutant===true))return null;
 if(typeof enemy.species==='string'&&Object.prototype.hasOwnProperty.call(bank.species,enemy.species))return enemy.species;
 return aliases.get(normalize(enemy.name))||null;
};
root.COMBAT_MUTANT_SOUND_BANK=bank;
if(typeof module!=='undefined')module.exports=bank;
})(typeof window!=='undefined'?window:globalThis);
