'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..');
const catalog=require('../images/combat/catalog.json');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const match=html.match(/const mutants = (\[[\s\S]*?\n    \]);/);
if(!match)throw Error('Cannot locate the gameplay mutant catalog');
const mutants=vm.runInNewContext(match[1]);
if(catalog.species.length!==29||catalog.entries.length!==57||mutants.length!==57)throw Error('Review mutant sound coverage for the changed roster');
const species={};
for(const source of catalog.species){
 const aliases=[];
 for(let i=0;i<catalog.entries.length;i++)if(catalog.entries[i].species===source.id){
  if(catalog.entries[i].tier!==mutants[i].tier)throw Error('Mutant catalog order changed: '+source.id);
  aliases.push(mutants[i].name,catalog.entries[i].name);
 }
 const profile=event=>({files:[1,2,3].map(n=>source.id+'-'+event+'-'+n+'.mp3'),gain:.85,...(event==='attack'?{impactMs:120}:{})});
 species[source.id]={name:aliases[0],tier:source.tier,aliases:[...new Set(aliases)],hurt:profile('hurt'),attack:profile('attack')};
}
const bank={version:'combat-mutants-20260929-v1',base:'audio/mutants/',species};
const script=`/* Generated by tools/build_mutant_sound_manifest.cjs. */
(function(root){
'use strict';
const bank=${JSON.stringify(bank,null,2)};
// Male and female names share one species bank. Gameplay and art spellings
// differ for some species, so audio resolves independently of visual readiness.
const normalize=value=>String(value||'').normalize('NFC').toLowerCase().replace(/ё/g,'е').replace(/[\\s\\-–—]+/g,'');
const aliases=new Map();
for(const [id,species] of Object.entries(bank.species))for(const alias of species.aliases){
 const key=normalize(alias);
 if(aliases.has(key)&&aliases.get(key)!==id)throw Error('Ambiguous mutant sound alias: '+alias);
 aliases.set(key,id);
}
bank.resolve=function(enemy){
 if(!enemy||enemy.kind==='npc'||!(enemy.kind==='mutant'||enemy.mutant===true||enemy.isMutant===true))return null;
 if(typeof enemy.species==='string'&&Object.prototype.hasOwnProperty.call(bank.species,enemy.species))return enemy.species;
 return aliases.get(normalize(enemy.name))||null;
};
root.COMBAT_MUTANT_SOUND_BANK=bank;
if(typeof module!=='undefined')module.exports=bank;
})(typeof window!=='undefined'?window:globalThis);
`;
fs.writeFileSync(path.join(root,'audio/combat-mutants.js'),script);
console.log('Built 29 mutant species, 57 gameplay names, 87 hurt and 87 attack variants');
