// Candidate-only scene review: production files are not replaced.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const {createCanvas,Image}=require('@napi-rs/canvas');
const root=path.resolve(__dirname,'..'),out=path.join(root,'.validation/new-hands-scene');fs.mkdirSync(out,{recursive:true});
let now=1000,frame,canvas;const events=[];const el=()=>({hidden:false,setAttribute(){},replaceChildren(){}}),host=el();
const document={hidden:false,getElementById:()=>host,addEventListener(){},createElement(n){if(n!=='canvas')return el();canvas=createCanvas(1536,1024);canvas.setAttribute=()=>{};return canvas;}};
function LocalImage(){const im=new Image(),set=Object.getOwnPropertyDescriptor(Image.prototype,'src').set;Object.defineProperty(im,'src',{set(url){set.call(im,path.join(root,url.split('?')[0]));}});return im;}
const catalog=require('../images/combat/catalog.json');const window={document,COMBAT_ASSETS:catalog,matchMedia:()=>({matches:false}),CombatAssets:{getVisuals:()=>({ready:true,species:'boar',background:'images/combat/backgrounds/boar/1.png',mutant:'images/combat/mutants/boar.png'})}};
const context=vm.createContext({window,document,Image:LocalImage,performance:{now:()=>now},console,setTimeout,clearTimeout,requestAnimationFrame:f=>{frame=f;return 1;},cancelAnimationFrame:()=>{frame=null;}});
for(const p of ['layout.js','effects.js','scene.js'])vm.runInContext(fs.readFileSync(path.join(root,'asset_sources/hand_transparency_review/runtime-snapshot',p),'utf8'),context);
const target={x:695,y:650},muzzle={x:1050,y:750,angle:Math.atan2(target.y-750,target.x-1050)};
window.CombatModular={resolve(id,armor){if(![75,76].includes(armor))return null;const dir=`asset_sources/combat_hand_repair/anatomy-${armor}`;const pair=require(path.join(root,dir,'all-pairs.json')).find(p=>p.weapon===id),profile=require(path.join(root,dir,'profile-v3.json'));
return {weapon:`images/combat/modular/weapons/${id}.png`,hand:`${dir}/hand-only-v3.webp`,pair,profile,muzzle};},drawForeground(ctx,gun,hand,v){const p=v.pair,pr=v.profile,mx=(p.muzzle.x-p.camera.x)/p.camera.scale,my=(p.muzzle.y-p.camera.y)/p.camera.scale;ctx.save();ctx.translate(muzzle.x,muzzle.y);ctx.rotate(muzzle.angle-p.muzzle.angle);ctx.scale(.45,.45);ctx.translate(-mx,-my);ctx.drawImage(hand,0,0);ctx.drawImage(gun,p.fit.x,p.fit.y,p.fit.width,p.fit.height);ctx.save();ctx.beginPath();for(const raw of pr.frontContours){const poly=raw.map(([x,y])=>[x*pr.scale+pr.x,y*pr.scale+pr.y]),a=poly.at(-1),b=poly[0];ctx.moveTo((a[0]+b[0])/2,(a[1]+b[1])/2);poly.forEach(([x,y],j)=>{const q=poly[(j+1)%poly.length];ctx.quadraticCurveTo(x,y,(x+q[0])/2,(y+q[1])/2);});ctx.closePath();}ctx.clip();ctx.drawImage(hand,0,0);ctx.restore();ctx.restore();return true;}};
const shot=window.CombatEffects.drawShot;window.CombatEffects.drawShot=(ctx,r,t,id,w,m)=>{events.push({t,recoil:ctx.getTransform().f,m});return shot(ctx,r,t,id,w,m);};
(async()=>{const results=[];for(const armor of [75,76])for(const weapon of catalog.pistols){now+=2000;const token=`${armor}-${weapon.id}`;assert(await window.CombatScene.show({armor,weaponId:weapon.id,enemy:{battleToken:token,name:'Кабан',hp:100}}));fs.writeFileSync(path.join(out,`${token}-idle.jpg`),canvas.toBuffer('image/jpeg'));window.CombatScene.react(token,{success:true,enemyHp:90},'attack');const start=now;for(const t of [0,40,89,90,150,240]){now=start+t;assert(frame);frame(now);const e=events.at(-1);assert.equal(e.t,t);assert(Math.abs(e.recoil-Math.sin(Math.PI*Math.min(1,t/220))*12)<.001);assert.equal(e.m.x,muzzle.x);assert.equal(e.m.y,muzzle.y);if(t===40)fs.writeFileSync(path.join(out,`${token}-shot.jpg`),canvas.toBuffer('image/jpeg'));}results.push({armor,weapon:weapon.id,phases:6,recoil:'passed',muzzle,target,scope:'candidate renderer in saved actual scene; not production'});window.CombatScene.hide();}fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));console.log('52 scene combinations, 312 recoil phases passed');})().catch(e=>{console.error(e);process.exitCode=1;});
