// Exercise production scene and modular renderer using local assets.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const {createCanvas,Image}=require('@napi-rs/canvas');
const root=path.resolve(__dirname,'..'),out=path.join(root,'.validation/new-hands-scene');fs.mkdirSync(out,{recursive:true});
let now=1000,frame,canvas;const events=[];const el=()=>({hidden:false,setAttribute(){},replaceChildren(){}}),host=el();
const document={hidden:false,getElementById:()=>host,addEventListener(){},createElement(n){if(n!=='canvas')return el();canvas=createCanvas(1536,1024);canvas.setAttribute=()=>{};return canvas;}};
function LocalImage(){const im=new Image(),set=Object.getOwnPropertyDescriptor(Image.prototype,'src').set;Object.defineProperty(im,'src',{set(url){set.call(im,path.join(root,url.split('?')[0]));}});return im;}
const catalog=require('../images/combat/catalog.json');const window={document,COMBAT_ASSETS:catalog,matchMedia:()=>({matches:false}),CombatAssets:{getVisuals:()=>({ready:true,species:'boar',background:'images/combat/backgrounds/boar/1.png',mutant:'images/combat/mutants/boar.png'})}};
const context=vm.createContext({window,document,Image:LocalImage,performance:{now:()=>now},console,setTimeout,clearTimeout,requestAnimationFrame:f=>{frame=f;return 1;},cancelAnimationFrame:()=>{frame=null;}});
for(const p of ['layout.js','effects.js','modular/hands-75-76.js','scene.js'])vm.runInContext(fs.readFileSync(path.join(root,'images/combat',p),'utf8'),context);
const target={x:695,y:650},muzzle={x:1050,y:750,angle:Math.atan2(target.y-750,target.x-1050)};
for(const armor of [1,2,74,77,96])assert.equal(window.CombatModular.resolve(1,armor,'boar'),null);
assert.equal(window.CombatModular.resolve(999,75,'boar'),null);
for(const species of Object.keys(window.CombatLayout.layout.creatures))for(const armor of [75,76])for(const weapon of catalog.pistols){const v=window.CombatModular.resolve(weapon.id,armor,species);const dx=v.target.x-v.muzzle.x,dy=v.target.y-v.muzzle.y;assert(Math.abs(dx*Math.sin(v.muzzle.angle)-dy*Math.cos(v.muzzle.angle))<.0001);assert(dx*Math.cos(v.muzzle.angle)+dy*Math.sin(v.muzzle.angle)>0);}
const shot=window.CombatEffects.drawShot;window.CombatEffects.drawShot=(ctx,r,t,id,w,m)=>{events.push({t,recoil:ctx.getTransform().f,m});return shot(ctx,r,t,id,w,m);};
(async()=>{const results=[];for(const armor of [75,76])for(const weapon of catalog.pistols){now+=2000;const token=`${armor}-${weapon.id}`;assert(await window.CombatScene.show({armor,weaponId:weapon.id,enemy:{battleToken:token,name:'Кабан',hp:100}}));fs.writeFileSync(path.join(out,`${token}-idle.jpg`),canvas.toBuffer('image/jpeg'));window.CombatScene.react(token,{success:true,enemyHp:90},'attack');const start=now;for(const t of [0,40,89,90,150,240]){now=start+t;assert(frame);frame(now);const e=events.at(-1);assert.equal(e.t,t);assert(Math.abs(e.recoil-Math.sin(Math.PI*Math.min(1,t/220))*12)<.001);assert.equal(e.m.x,muzzle.x);assert.equal(e.m.y,muzzle.y);if(t===40)fs.writeFileSync(path.join(out,`${token}-shot.jpg`),canvas.toBuffer('image/jpeg'));}results.push({armor,weapon:weapon.id,phases:6,recoil:'passed',muzzle,target,scope:'production scene and modular renderer; local headless canvas'});window.CombatScene.hide();}fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));console.log('52 scene combinations, 312 recoil phases passed');})().catch(e=>{console.error(e);process.exitCode=1;});
