const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');const{createCanvas,loadImage}=require('@napi-rs/canvas');
const version=process.env.HAND_VERSION||'v2';
const armor=Number(process.argv[2]||74);const root=path.resolve(__dirname,'..'),out=path.join(root,'asset_sources/combat_hand_repair/anatomy-'+armor);

const window={};const context=vm.createContext({window});for(const p of ['layout.js','effects.js','modular/data.js'])vm.runInContext(fs.readFileSync(path.join(root,'asset_sources/hand_transparency_review/runtime-snapshot',p),'utf8'),context);
(async()=>{const base=JSON.parse(fs.readFileSync(path.join(root,'asset_sources/combat_hand_repair/anatomy-74/modular-placement.json'))),fits=JSON.parse(fs.readFileSync(path.join(root,'asset_sources/prepared_hand_pack/fits.json'))),hand=await loadImage(path.join(out,'hand-only-'+version+'.webp'));const profile=fs.existsSync(path.join(out,version==='v2'?'profile.json':'profile-'+version+'.json'))?JSON.parse(fs.readFileSync(path.join(out,version==='v2'?'profile.json':'profile-'+version+'.json'))):{scale:1,x:0,y:0};if(profile.frontContours)base.frontContours=profile.frontContours; base.frontContours=base.frontContours.map(p=>p.map(([x,y])=>[x*profile.scale+profile.x,y*profile.scale+profile.y]));const scale=1250/fits[1].width,entries=[];let sheet,sc,i=0;
for(const[id,f]of Object.entries(fits)){if(i%6===0){sheet=createCanvas(1536,1536);sc=sheet.getContext('2d');}
const fit={x:base.fit.x+(f.x-fits[1].x)*scale,y:base.fit.y+(f.y-fits[1].y)*scale,width:f.width*scale,height:f.height*scale};fit.x=fit.x*profile.scale+profile.x;fit.y=fit.y*profile.scale+profile.y;fit.width*=profile.scale;fit.height*=profile.scale;const gun=await loadImage(path.join(root,`images/combat/modular/weapons/${id}.png`));const c=createCanvas(1536,1024),ctx=c.getContext('2d');ctx.setTransform(.7,0,0,.7,460,307.2);ctx.drawImage(hand,0,0);ctx.drawImage(gun,fit.x,fit.y,fit.width,fit.height);ctx.save();ctx.beginPath();for(const poly of base.frontContours){const a=poly.at(-1),b=poly[0];ctx.moveTo((a[0]+b[0])/2,(a[1]+b[1])/2);poly.forEach(([x,y],j)=>{const n=poly[(j+1)%poly.length];ctx.quadraticCurveTo(x,y,(x+n[0])/2,(y+n[1])/2);});ctx.closePath();}ctx.clip();ctx.drawImage(hand,0,0);ctx.restore();
const x=i%2*768,y=Math.floor(i%6/2)*512;sc.fillStyle=i%2?'#dddcd5':'#23394a';sc.fillRect(x,y,768,512);sc.drawImage(c,0,0,1536,1024,x,y+25,730,487);sc.fillStyle=i%2?'#111':'#fff';sc.font='22px sans-serif';sc.fillText('Armor'+armor+' / weapon '+id,x+8,y+23);
fs.writeFileSync(path.join(out,`pair-${id}.png`),c.toBuffer('image/png'));const [mx,my,angle,mw,mh]=window.COMBAT_MODULAR_DATA.weapons[id].sourceMuzzle;
const muzzle={x:460+.7*(fit.x+mx*fit.width/mw),y:307.2+.7*(fit.y+my*fit.height/mh),angle};const flashChecks=[];
for(const ms of [0,40,89,90,150,240]){const fc=createCanvas(1536,1024),fx=fc.getContext('2d');window.CombatEffects.drawShot(fx,{shot:true},ms,Number(id),{suppressed:false},muzzle);const pixels=fx.getImageData(0,0,1536,1024).data;let visible=0,outside=0;for(let k=3;k<pixels.length;k+=4)if(pixels[k]){visible++;const q=(k-3)/4;if(Math.hypot(q%1536-muzzle.x,Math.floor(q/1536)-muzzle.y)>97)outside++;}assert.equal(outside,0);assert.equal(visible>0,ms<90);flashChecks.push({ms,visible,outside});if(ms===0){const shot=createCanvas(1536,1024),sx=shot.getContext('2d');sx.fillStyle='#253746';sx.fillRect(0,0,1536,1024);sx.drawImage(c,0,0);sx.drawImage(fc,0,0);fs.writeFileSync(path.join(out,`shot-${id}.jpg`),shot.toBuffer('image/jpeg'));}}
entries.push({weapon:Number(id),armor,fit,camera:{scale:.7,x:460,y:307.2},muzzle,flashChecks,status:'rendered-awaiting-individual-visual-review'});i++;if(i%6===0||i===Object.keys(fits).length)fs.writeFileSync(path.join(out,`all-pairs-${Math.ceil(i/6)}.jpg`),sheet.toBuffer('image/jpeg'));
}fs.writeFileSync(path.join(out,'all-pairs.json'),JSON.stringify(entries,null,2));console.log('Rendered '+i+' pairs');})();
